<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>Bisa.Pagination.EFCore</RootNamespace>
    <PackageId>Bisa.Pagination.EFCore</PackageId>
    <Description>Async implementation of pagination (Offset and Cursor) for Entity Framework Core based on Bisa.Pagination.Core.</Description>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\Bisa.Pagination.Abstractions\Bisa.Pagination.Abstractions.csproj" />
    <ProjectReference Include="..\Bisa.Pagination.Core\Bisa.Pagination.Core.csproj" />
  </ItemGroup>

</Project>
