<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <RootNamespace>Bisa.Pagination.Abstractions</RootNamespace>
        <PackageId>Bisa.Pagination.Abstractions</PackageId>
        <Description>Contracts and basic models of the Bisa.Pagination library (no dependency on a particular database or framework)</Description>
    </PropertyGroup>

</Project>
